blank_issues_enabled: false
contact_links:
  - name: 🛡️ Divulgation Responsable de Sécurité
    url: mailto:contact@signa.ci
    about: Pour signaler une vulnérabilité de sécurité de façon privée et confidentielle.
