BEGIN;
CREATE OR REPLACE FUNCTION public.public_shift_coordinate(p_report_id uuid,p_value double precision,p_axis text) RETURNS double precision LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE v_secret text; v_hash bytea; v_byte integer; v_magnitude double precision; v_sign double precision;
BEGIN
 IF p_value IS NULL THEN RETURN NULL; END IF;
 SELECT decrypted_secret INTO v_secret FROM vault.decrypted_secrets WHERE name='civic_signal_public_coordinate_pepper' LIMIT 1;
 IF v_secret IS NULL THEN RETURN round(p_value::numeric,2)::double precision; END IF;
 v_hash:=hmac(p_report_id::text||':'||coalesce(p_axis,''),v_secret,'sha256'); v_byte:=get_byte(v_hash,0); v_magnitude:=0.0015+(get_byte(v_hash,1)::double precision/255.0)*0.0010; v_sign:=CASE WHEN (v_byte%2)=0 THEN 1 ELSE -1 END;
 RETURN round((p_value+v_sign*v_magnitude)::numeric,6)::double precision;
END; $$;
REVOKE EXECUTE ON FUNCTION public.public_shift_coordinate(uuid,double precision,text) FROM public,anon,authenticated;
CREATE OR REPLACE FUNCTION public.get_public_reports() RETURNS TABLE(id uuid,service_type text,report_category text,description text,location text,latitude double precision,longitude double precision,urgency text,status text,reporter_type text,start_time timestamptz,verifications integer,created_at timestamptz,resolved_at timestamptz) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $$ SELECT r.id,r.service_type,r.report_category,left(r.description,120),r.location,public.public_shift_coordinate(r.id,r.latitude,'lat'),public.public_shift_coordinate(r.id,r.longitude,'lon'),r.urgency,r.status,r.reporter_type,r.start_time,r.verifications,r.created_at,r.resolved_at FROM public.reports r WHERE r.report_category='outage' AND r.validated=true AND r.status IN ('active','chronic','in_progress','open','verified') ORDER BY r.created_at DESC LIMIT 100; $$;
CREATE OR REPLACE FUNCTION public.get_public_infrastructure_reports(p_commune text DEFAULT NULL,p_limit integer DEFAULT 150,p_offset integer DEFAULT 0) RETURNS TABLE(id uuid,service_type text,report_category text,description text,location text,commune text,quartier text,status text,urgency text,created_at timestamptz,resolved_at timestamptz,photo_url text,photo_urls text[],verifications integer,repair_verifications integer,support_count integer,impacted_people integer,reporter_type text,latitude double precision,longitude double precision,ticket_code text,operator_name text,operator_reference text,operator_last_note text,estimated_resolution_time timestamptz) LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $$ SELECT r.id,r.service_type,r.report_category,r.description,r.location,r.commune,r.quartier,r.status,r.urgency,r.created_at,r.resolved_at,NULL::text,NULL::text[],r.verifications,r.repair_verifications,r.support_count,r.impacted_people,r.reporter_type,public.public_shift_coordinate(r.id,r.latitude,'lat'),public.public_shift_coordinate(r.id,r.longitude,'lon'),r.ticket_code,r.operator_name,r.operator_reference,r.operator_last_note,r.estimated_resolution_time FROM public.reports r WHERE r.validated=true AND (r.report_category='infrastructure' OR r.service_type IN ('mairie','voirie') OR r.description ILIKE '%lampadaire%' OR r.description ILIKE '%éclairage%' OR r.description ILIKE '%eclairage%' OR r.description ILIKE '%poteau%' OR r.description ILIKE '%caniveau%' OR r.description ILIKE '%nid de poule%' OR r.description ILIKE '%fuite%') AND (p_commune IS NULL OR r.commune ILIKE p_commune) ORDER BY r.created_at DESC LIMIT least(greatest(p_limit,1),150) OFFSET greatest(p_offset,0); $$;
DROP POLICY IF EXISTS "Public can read validated infrastructure reports" ON public.reports;
DROP POLICY IF EXISTS "Public can read visible comments" ON public.report_comments;
CREATE POLICY "Public can read visible comments" ON public.report_comments FOR SELECT TO public USING (hidden=false AND EXISTS (SELECT 1 FROM public.reports r WHERE r.id=report_comments.report_id AND r.validated=true));
COMMIT;
