import {
  electriciteIcon,
  eauIcon,
  lampadaireIcon,
  poteauElectriqueIcon,
  cieHazardIcon,
  cieAutreIcon,
  canalisationIcon,
  fuiteEauIcon,
  sodeciAutreIcon,
  voirieIcon,
  caniveauIcon,
  trottoirIcon,
  depotOrduresIcon,
  mairieAutreIcon,
} from "@/lib/infra-icons";
import type { ReportTypeConfig } from "./types";

export const REPORT_TYPES: ReportTypeConfig[] = [
  // ─── Coupures de service ───────────────────────────────────────────
  {
    id: "electricity_outage",
    emoji: "⚡",
    label: "Coupure d'électricité",
    description: "Interruption du courant chez vous ou dans la zone",
    image: electriciteIcon,
    color: "#F59E0B",
    serviceType: "electricity",
    reportCategory: "outage",
    defaultDesc: (c) => `Coupure d'électricité à ${c}`,
  },
  {
    id: "water_outage",
    emoji: "💧",
    label: "Coupure d'eau",
    description: "Interruption de distribution d'eau potable",
    image: eauIcon,
    color: "#3B82F6",
    serviceType: "water",
    reportCategory: "outage",
    defaultDesc: (c) => `Coupure d'eau à ${c}`,
  },

  // ─── CIE (Électricité & Éclairage Public) ──────────────────────────
  {
    id: "street_light",
    emoji: "💡",
    label: "Lampadaires & Éclairage public",
    description: "Lampadaire cassé, éteint ou éclairage public hors service",
    image: lampadaireIcon,
    color: "#EAB308",
    serviceType: "electricity",
    reportCategory: "infrastructure",
    operator: "CIE",
    defaultDesc: (c) => `Lampadaire / Éclairage public hors service à ${c}`,
  },
  {
    id: "cie_pole",
    emoji: "🗼",
    label: "Poteaux / Pylônes",
    description: "Poteau penché, câble électrique à terre, pylône à risque",
    image: poteauElectriqueIcon,
    color: "#F59E0B",
    serviceType: "electricity",
    reportCategory: "infrastructure",
    operator: "CIE",
    defaultDesc: (c) => `Poteau / Pylône électrique dangereux à ${c}`,
  },
  {
    id: "cie_hazard",
    emoji: "⚠️",
    label: "Branchements dangereux",
    description: "Fils nus, étincelles, installation à risque élevé",
    image: cieHazardIcon,
    color: "#EF4444",
    serviceType: "electricity",
    reportCategory: "infrastructure",
    operator: "CIE",
    defaultDesc: (c) => `Branchement électrique dangereux à ${c}`,
  },
  {
    id: "cie_other",
    emoji: "🚧",
    label: "Autres incidents CIE",
    description: "Autre anomalie sur le réseau d'électricité",
    image: cieAutreIcon,
    color: "#F97316",
    serviceType: "electricity",
    reportCategory: "infrastructure",
    operator: "CIE",
    defaultDesc: (c) => `Incident réseau électrique CIE à ${c}`,
  },

  // ─── SODECI (Eau Potable & Assainissement) ────────────────────────
  {
    id: "canalisation_sodeci",
    emoji: "🚰",
    label: "Canalisation publique",
    description: "Égout bouché, débordement de vos regards",
    image: canalisationIcon,
    color: "#0284C7",
    serviceType: "water",
    reportCategory: "infrastructure",
    operator: "SODECI",
    defaultDesc: (c) => `Canalisation publique / Égout bouché à ${c}`,
  },
  {
    id: "water_leak",
    emoji: "🚿",
    label: "Fuite d'eau",
    description: "Fuite d'eau à l'extérieur de votre maison",
    image: fuiteEauIcon,
    color: "#06B6D4",
    serviceType: "water",
    reportCategory: "infrastructure",
    operator: "SODECI",
    defaultDesc: (c) => `Fuite d'eau à l'extérieur de la maison à ${c}`,
  },
  {
    id: "sodeci_other",
    emoji: "💧",
    label: "Autre incident SODECI",
    description: "Incident sur le réseau d'eau potable",
    image: sodeciAutreIcon,
    color: "#3B82F6",
    serviceType: "water",
    reportCategory: "infrastructure",
    operator: "SODECI",
    defaultDesc: (c) => `Incident réseau d'eau potable SODECI à ${c}`,
  },

  // ─── MAIRIE (Voirie & Salubrité) ──────────────────────────────────
  {
    id: "pothole",
    emoji: "🛣️",
    label: "Nid de poule",
    description: "Trou sur la chaussée, bitume dégradé",
    image: voirieIcon,
    color: "#10B981",
    serviceType: "mairie" as any,
    reportCategory: "infrastructure",
    operator: "MAIRIE",
    defaultDesc: (c) => `Nid de poule / route dégradée à ${c}`,
  },
  {
    id: "drain_blocked",
    emoji: "🚧",
    label: "Caniveau bouché",
    description: "Caniveau obstrué, eau stagnante sur la voie publique",
    image: caniveauIcon,
    color: "#10B981",
    serviceType: "mairie" as any,
    reportCategory: "infrastructure",
    operator: "MAIRIE",
    defaultDesc: (c) => `Caniveau bouché à ${c}`,
  },
  {
    id: "road_damage",
    emoji: "🛤️",
    label: "Voirie & Trottoirs",
    description: "Trottoir cassé, pavés abîmés, glissière endommagée",
    image: trottoirIcon,
    color: "#8B5CF6",
    serviceType: "mairie" as any,
    reportCategory: "infrastructure",
    operator: "MAIRIE",
    defaultDesc: (c) => `Voirie / trottoir dégradé à ${c}`,
  },
  {
    id: "illegal_dump",
    emoji: "🗑️",
    label: "Dépôt sauvage & Ordures",
    description: "Ordures ou déchets non ramassés sur le domaine public",
    image: depotOrduresIcon,
    color: "#10B981",
    serviceType: "mairie" as any,
    reportCategory: "infrastructure",
    operator: "MAIRIE",
    defaultDesc: (c) => `Dépôt sauvage d'ordures à ${c}`,
  },
  {
    id: "other",
    emoji: "🏗️",
    label: "Autre (Mairie)",
    description: "Autre anomalie relevant des services municipaux",
    image: mairieAutreIcon,
    color: "#6B7280",
    serviceType: "mairie" as any,
    reportCategory: "infrastructure",
    operator: "MAIRIE",
    defaultDesc: (c) => `Signalement voirie / mairie à ${c}`,
  },
];
